version: '3'
services:
  postgres:
    image: postgres:10
    restart: always
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev
      - POSTGRES_DB=eventfinder
      - PGDATA=/tmp
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
  redis:
    image: redis
    restart: always
    volumes:
      - ./data/redis:/var/lib/redis/data
    ports:
        - 6379:6379
    command: redis-server --appendonly yes
  app:
    image: gcr.io/eventfinder-239405/eventfinder-app:latest
    restart: always
    build: .
    volumes:
      - .:/app
    ports:
      - 8080:8080
      - 5000:5000
    depends_on:
      - postgres
      - redis
    command: ["python", "app.py", "run"]